feat: add support for computed_members
mineiros-io/terraform-google-secret-manager pull request #20
Opened 2022-12-13 14:25 UTC by waxb

- chore: changelog updated
- feat: add support for `computed_members`

2023-01-02 21:00 UTC, mariux requested changes

2023-01-02 21:00 UTC, mariux commented on main.tf
> +                kms_key_name = customer_managed_encryption.value
looks like breaking the functionality?

2023-01-02 21:16 UTC, waxb commented on main.tf
> +                kms_key_name = customer_managed_encryption.value
it was broken before

2023-01-03 11:36 UTC, mariux requested changes

2023-01-03 11:36 UTC, mariux commented on main.tf
>                for_each = try(replicas.value.customer_managed_encryption, [])
```suggestion
              for_each = try([replicas.value.customer_managed_encryption], [])
```

2023-01-03 11:36 UTC, mariux commented on main.tf
> +                kms_key_name = customer_managed_encryption.value
```suggestion
                kms_key_name = customer_managed_encryption.value.kms_key_name
```

2023-01-03 11:38 UTC, mariux approved these changes
lgtm

2023-01-03 13:18 UTC, merged